CREATE OR REPLACE DIRECTORY DM_DUMP AS '/opt/oracle/models';

BEGIN
   DBMS_VECTOR.LOAD_ONNX_MODEL(
        directory => 'DM_DUMP',
        file_name => 'all_MiniLM_L12_v2.onnx',
        model_name => 'ALL_MINILM_L12_V2');
END;
/

CREATE TABLE documents (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR2(255),
    content CLOB,
    embedding VECTOR
);

SELECT * FROM documents;


-- TRUNCATE TABLE documents;

commit;

-- restart dupa comanda
ALTER SYSTEM SET VECTOR_MEMORY_SIZE = 1G SCOPE=SPFILE;